<a href="https://colab.research.google.com/github/OlhaZahrebelna/python_for_ds_task/blob/main/ZahrebelnaOlha_%22HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8)_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

In [2]:
vector = np.random.rand(10)

In [3]:
random_vector = np.random.uniform(0, 1, 10)

In [4]:
matrix = np.array([[11, 14, 17],
                  [20, 23, 26],
                  [29, 32, 35]])

In [5]:
print('vector: ', vector, 'shape: ', vector.shape)
print('random_vector: ', random_vector, 'shape: ', random_vector.shape)
print('matrix: ', matrix, 'shape: ', matrix.shape)

vector:  [0.8658825  0.69470211 0.8343485  0.47468885 0.04544101 0.9469826
 0.30847044 0.43287953 0.94929686 0.99832807] shape:  (10,)
random_vector:  [0.41133097 0.16567098 0.56728695 0.18942919 0.48512886 0.71745959
 0.26854675 0.65413247 0.19861261 0.08510614] shape:  (10,)
matrix:  [[11 14 17]
 [20 23 26]
 [29 32 35]] shape:  (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [6]:
print('vector + 10: ', np.round(vector + 10, 2))

vector + 10:  [10.87 10.69 10.83 10.47 10.05 10.95 10.31 10.43 10.95 11.  ]


In [7]:
print('matrix * 2: ', matrix * 2)

matrix * 2:  [[22 28 34]
 [40 46 52]
 [58 64 70]]


In [8]:
squere_vector = np.square(vector)
print('squere_vector: ', squere_vector)

squere_vector:  [0.7497525  0.48261102 0.69613742 0.22532951 0.00206488 0.89677605
 0.09515401 0.18738469 0.90116452 0.99665893]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [9]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [10]:
result_matrix = B.dot(A)
print('result_matrix: ', result_matrix, 'shape: ', result_matrix.shape)

result_matrix:  [[0.7281 0.5202]
 [0.2034 0.2846]] shape:  (2, 2)


In [11]:
mult_c_matrix = np.dot(result_matrix, C)
print('mult_c_matrix: ', mult_c_matrix, 'shape: ', mult_c_matrix.shape)

mult_c_matrix:  [[0.5202]
 [0.2846]] shape:  (2, 1)


In [12]:
mult_c_matrix2 = result_matrix.dot(C)
print('mult_c_matrix2: ', mult_c_matrix2, 'shape: ', mult_c_matrix2.shape)

mult_c_matrix2:  [[0.5202]
 [0.2846]] shape:  (2, 1)


In [13]:
mulyt_d_matrix = np.dot(result_matrix, D)
print('mulyt_d_matrix: ', mulyt_d_matrix, 'shape: ', mulyt_d_matrix.shape)

mulyt_d_matrix:  [[0.5202 0.7281]
 [0.2846 0.2034]] shape:  (2, 2)



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [14]:
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [15]:
vector

array([0.8658825 , 0.69470211, 0.8343485 , 0.47468885, 0.04544101,
       0.9469826 , 0.30847044, 0.43287953, 0.94929686, 0.99832807])

In [16]:
np.shape(vector)

(10,)

In [17]:
vector.T

array([0.8658825 , 0.69470211, 0.8343485 , 0.47468885, 0.04544101,
       0.9469826 , 0.30847044, 0.43287953, 0.94929686, 0.99832807])

In [18]:
np.shape(vector.T)

(10,)

Ні,немає змін, бо це одновимірний масив.

In [19]:
column_vector = np.expand_dims(vector, axis=1)
print('column_vector: ', column_vector, 'shape: ', column_vector.shape)


column_vector:  [[0.8658825 ]
 [0.69470211]
 [0.8343485 ]
 [0.47468885]
 [0.04544101]
 [0.9469826 ]
 [0.30847044]
 [0.43287953]
 [0.94929686]
 [0.99832807]] shape:  (10, 1)


column_vector є виглядає як вектор колонка, а vector це вектор рядок.

In [20]:
column_vector.T

array([[0.8658825 , 0.69470211, 0.8343485 , 0.47468885, 0.04544101,
        0.9469826 , 0.30847044, 0.43287953, 0.94929686, 0.99832807]])

In [21]:
np.shape(column_vector.T)

(1, 10)